
package daragh.serviceif.com;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ToystoreIFService", targetNamespace = "http://com.serviceif.daragh/", wsdlLocation = "http://localhost:8080/ToyStoreService/ToystoreIFService?wsdl")
public class ToystoreIFService
    extends Service
{

    private final static URL TOYSTOREIFSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOYSTOREIFSERVICE_EXCEPTION;
    private final static QName TOYSTOREIFSERVICE_QNAME = new QName("http://com.serviceif.daragh/", "ToystoreIFService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ToyStoreService/ToystoreIFService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOYSTOREIFSERVICE_WSDL_LOCATION = url;
        TOYSTOREIFSERVICE_EXCEPTION = e;
    }

    public ToystoreIFService() {
        super(__getWsdlLocation(), TOYSTOREIFSERVICE_QNAME);
    }

    public ToystoreIFService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOYSTOREIFSERVICE_QNAME, features);
    }

    public ToystoreIFService(URL wsdlLocation) {
        super(wsdlLocation, TOYSTOREIFSERVICE_QNAME);
    }

    public ToystoreIFService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOYSTOREIFSERVICE_QNAME, features);
    }

    public ToystoreIFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ToystoreIFService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ToystoreIF
     */
    @WebEndpoint(name = "ToystoreIFPort")
    public ToystoreIF getToystoreIFPort() {
        return super.getPort(new QName("http://com.serviceif.daragh/", "ToystoreIFPort"), ToystoreIF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ToystoreIF
     */
    @WebEndpoint(name = "ToystoreIFPort")
    public ToystoreIF getToystoreIFPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.serviceif.daragh/", "ToystoreIFPort"), ToystoreIF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOYSTOREIFSERVICE_EXCEPTION!= null) {
            throw TOYSTOREIFSERVICE_EXCEPTION;
        }
        return TOYSTOREIFSERVICE_WSDL_LOCATION;
    }

}
