
package daragh.serviceif.com;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ToystoreIF", targetNamespace = "http://com.serviceif.daragh/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ToystoreIF {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://com.serviceif.daragh/", className = "daragh.serviceif.com.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://com.serviceif.daragh/", className = "daragh.serviceif.com.UpdateResponse")
    @Action(input = "http://com.serviceif.daragh/ToystoreIF/updateRequest", output = "http://com.serviceif.daragh/ToystoreIF/updateResponse")
    public boolean update(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://com.serviceif.daragh/", className = "daragh.serviceif.com.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://com.serviceif.daragh/", className = "daragh.serviceif.com.DeleteResponse")
    @Action(input = "http://com.serviceif.daragh/ToystoreIF/deleteRequest", output = "http://com.serviceif.daragh/ToystoreIF/deleteResponse")
    public boolean delete(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<daragh.serviceif.com.StockItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://com.serviceif.daragh/", className = "daragh.serviceif.com.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://com.serviceif.daragh/", className = "daragh.serviceif.com.ReadResponse")
    @Action(input = "http://com.serviceif.daragh/ToystoreIF/readRequest", output = "http://com.serviceif.daragh/ToystoreIF/readResponse")
    public List<StockItem> read();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://com.serviceif.daragh/", className = "daragh.serviceif.com.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://com.serviceif.daragh/", className = "daragh.serviceif.com.CreateResponse")
    @Action(input = "http://com.serviceif.daragh/ToystoreIF/createRequest", output = "http://com.serviceif.daragh/ToystoreIF/createResponse")
    public boolean create(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

}
